[package]
name = "aoc18_10"
version = "0.1.0"
authors = ["Sebastian Zivota <sebastian.zivota@mailbox.org>"]
edition = "2018"

[dependencies]
regex = "1"
re-parse = "0.1.0"
lazy_static = "1.2.0"

[dependencies.serde]
version = "1.0.82"
features = ["derive"]
